# Generated by Django 5.2.3 on 2025-07-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
